using Microsoft.EntityFrameworkCore;
using StudentServiceRequestSystem.Models;
using StudentServiceRequestSystem.Services;

namespace StudentServiceRequestSystem.Data;

public static class DbInitializer
{
    public static async Task InitializeAsync(ApplicationDbContext context, IPasswordHasherService passwordHasher, ILogger logger)
    {
        try
        {
            logger.LogInformation("Ensuring Supabase PostgreSQL database tables exist...");

            // Supabase already has internal tables (auth, storage, etc.), which causes EF Core's
            // EnsureCreated() to no-op. We explicitly execute idempotent DDL to create our application tables.
            const string createTablesSql = """
                CREATE TABLE IF NOT EXISTS "Users" (
                    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    "Name" character varying(100) NOT NULL,
                    "Email" character varying(150) NOT NULL,
                    "PasswordHash" character varying(255) NOT NULL,
                    "Role" character varying(20) NOT NULL,
                    "CreatedAt" timestamp with time zone NOT NULL DEFAULT (NOW())
                );

                CREATE UNIQUE INDEX IF NOT EXISTS "IX_Users_Email" ON "Users" ("Email");

                CREATE TABLE IF NOT EXISTS "ServiceRequests" (
                    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    "UserId" integer NOT NULL,
                    "RequestType" character varying(50) NOT NULL,
                    "Description" character varying(1000) NOT NULL,
                    "Status" character varying(30) NOT NULL,
                    "StaffRemarks" character varying(500),
                    "RequestDate" timestamp with time zone NOT NULL DEFAULT (NOW()),
                    "UpdatedAt" timestamp with time zone,
                    CONSTRAINT "FK_ServiceRequests_Users_UserId" FOREIGN KEY ("UserId") 
                        REFERENCES "Users" ("Id") ON DELETE CASCADE
                );

                CREATE INDEX IF NOT EXISTS "IX_ServiceRequests_UserId" ON "ServiceRequests" ("UserId");
            """;

            await context.Database.ExecuteSqlRawAsync(createTablesSql);
            logger.LogInformation("Supabase tables 'Users' and 'ServiceRequests' verified / created.");

            // 1. Seed Staff Account
            var staffEmail = "admin@university.com";
            var staffUser = await context.Users.FirstOrDefaultAsync(u => u.Email.ToLower() == staffEmail.ToLower());
            if (staffUser == null)
            {
                staffUser = new User
                {
                    Name = "University Staff Admin",
                    Email = staffEmail,
                    PasswordHash = passwordHasher.HashPassword("Admin@123456"),
                    Role = UserRole.Staff,
                    CreatedAt = DateTime.UtcNow
                };
                context.Users.Add(staffUser);
                await context.SaveChangesAsync();
                logger.LogInformation("Default Staff account created in Supabase: {Email}", staffEmail);
            }

            // 2. Seed Student Account
            var studentEmail = "student@iubat.edu";
            var studentUser = await context.Users.FirstOrDefaultAsync(u => u.Email.ToLower() == studentEmail.ToLower());
            if (studentUser == null)
            {
                studentUser = new User
                {
                    Name = "Sium Rahman",
                    Email = studentEmail,
                    PasswordHash = passwordHasher.HashPassword("Student@123456"),
                    Role = UserRole.Student,
                    CreatedAt = DateTime.UtcNow
                };
                context.Users.Add(studentUser);
                await context.SaveChangesAsync();
                logger.LogInformation("Sample Student account created in Supabase: {Email}", studentEmail);
            }

            // 3. Seed Sample Requests if none exist
            var hasRequests = await context.ServiceRequests.AnyAsync();
            if (!hasRequests && studentUser != null)
            {
                var sampleRequests = new List<ServiceRequest>
                {
                    new()
                    {
                        UserId = studentUser.Id,
                        RequestType = RequestType.IDCardReplacement,
                        Description = "My university student ID card was lost on university bus route 4. Please issue a replacement card as soon as possible.",
                        Status = RequestStatus.Pending,
                        RequestDate = DateTime.UtcNow.AddDays(-2),
                        StaffRemarks = null
                    },
                    new()
                    {
                        UserId = studentUser.Id,
                        RequestType = RequestType.TranscriptRequest,
                        Description = "Official academic transcript needed for higher study scholarship application. All semester grades up to Spring 2026 are completed.",
                        Status = RequestStatus.Processing,
                        RequestDate = DateTime.UtcNow.AddDays(-5),
                        UpdatedAt = DateTime.UtcNow.AddDays(-1),
                        StaffRemarks = "Transcript is under verification with the registrar office."
                    },
                    new()
                    {
                        UserId = studentUser.Id,
                        RequestType = RequestType.CertificateRequest,
                        Description = "Bonafide student certificate required for foreign internship visa processing.",
                        Status = RequestStatus.Completed,
                        RequestDate = DateTime.UtcNow.AddDays(-10),
                        UpdatedAt = DateTime.UtcNow.AddDays(-3),
                        StaffRemarks = "Certificate signed and ready for pickup at Counter 2."
                    }
                };

                context.ServiceRequests.AddRange(sampleRequests);
                await context.SaveChangesAsync();
                logger.LogInformation("Sample service requests seeded into Supabase successfully.");
            }

            logger.LogInformation("Database initialization and seeding completed successfully.");
        }
        catch (Exception ex)
        {
            logger.LogError(ex, "An error occurred while initializing the Supabase PostgreSQL database.");
            throw;
        }
    }
}
